import json
from pydantic import BaseModel
from typing import Optional, List, Dict, Any
from datetime import datetime
from fastapi import APIRouter, HTTPException

router = APIRouter()

class HindcastForecastRequest(BaseModel):
    spill_id: str
    centroid: List[float]
    observation_timestamp: datetime
    area_km2: float
    confidence: float
    source_satellite: str
    geojson_polygon: Dict[str, Any]
    forcing_mode: str
    oil_type: str
    mode: str

@router.get("/health")
async def health_check_v2():
    try:
        from agent2.physics.opendrift_wrapper import OPENDRIFT_AVAILABLE
        if OPENDRIFT_AVAILABLE:
            import opendrift
            od_version = opendrift.__version__
        else:
            od_version = None
    except ImportError:
        OPENDRIFT_AVAILABLE = False
        od_version = None
        
    return {
        "status": "ok",
        "agent1_model_loaded": True, # Hardcoded for now
        "agent2_ready": True,
        "opendrift_available": OPENDRIFT_AVAILABLE,
        "opendrift_version": od_version,
        "engine_active": "opendrift_openoil" if OPENDRIFT_AVAILABLE else "rk4_native"
    }

@router.post("/hindcast-forecast")
async def run_hindcast_forecast(req: HindcastForecastRequest):
    try:
        from agent2.pipeline import Agent2Pipeline
        from agent2.config import Agent2Config
        from agent2.contracts.spill_observation import SpillObservation
        from shapely.geometry import shape
        
        cfg = Agent2Config()
        cfg.oil_category = req.oil_type
        cfg.forcing.provider = req.forcing_mode
        
        pipeline = Agent2Pipeline(config=cfg)
        
        # Convert dict to SpillObservation
        geom = shape(req.geojson_polygon)
        spill = SpillObservation(
            spill_id=req.spill_id,
            observation_timestamp=req.observation_timestamp,
            geometry_geojson=req.geojson_polygon,
            area_km2=req.area_km2,
            confidence=req.confidence,
            source_satellite=req.source_satellite,
            metadata={}
        )
        
        result = pipeline.run(spill, mode=req.mode)
        
        res_dict = json.loads(result.model_dump_json())
        
        engine_used = "rk4_native"
        od_avail = False
        anim_frames = []
        weathering = []
        
        if result.hindcast and result.hindcast.enabled:
            engine_used = result.hindcast.engine_used or engine_used
            od_avail = result.hindcast.opendrift_available or od_avail
            if result.hindcast.animation_frames:
                anim_frames.extend(result.hindcast.animation_frames)
                
        if result.forecast and result.forecast.enabled:
            engine_used = result.forecast.engine_used or engine_used
            od_avail = result.forecast.opendrift_available or od_avail
            if result.forecast.animation_frames:
                anim_frames.extend(result.forecast.animation_frames)
            if result.forecast.weathering_timeseries:
                weathering.extend(result.forecast.weathering_timeseries)
                
        res_dict["engine_used"] = engine_used
        res_dict["opendrift_available"] = od_avail
        res_dict["animation_frames"] = anim_frames
        res_dict["weathering"] = weathering
        
        return res_dict
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/metocean")
async def get_metocean(bbox: str):
    try:
        from agent2.adapters.mock_forcing import MockEnvironmentalForcingProvider
        forcing = MockEnvironmentalForcingProvider()
        return {
            "wind": { "u": forcing.wind_u, "v": forcing.wind_v, "speed": 14.2, "dir": 245 },
            "current": { "u": forcing.current_u, "v": forcing.current_v, "speed": 0.42, "dir": 80 },
            "sst": 24.8
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/export/geojson")
async def export_geojson(req: Dict[str, Any]):
    return req.get("geojson_collection", {})

@router.post("/export/sitrep")
async def export_sitrep(req: Dict[str, Any]):
    md = f"# SITREP: Spill {req.get('spill_id', 'Unknown')}\n\nGenerated by OceanTrace Agent 2.\n"
    return {"markdown": md}
